### ISSUE TITLE
0 bpm

### ISSUE THREAD

**Issue by lisalrc** [FunOrange/circle-tracker#10]
![Capture](https://user-images.githubusercontent.com/68695513/88290152-990cde80-ccf6-11ea-8827-1c2e7222b6ad.PNG)
A lot of plays (about 90% of plays) have 0 bpm.

**Comment by DanBeast1337** [comment]
So I've looked a little further into this and it seems to be kinda random, but predictable. 

I tested it with all kinds of ranges for BPM. It turns out, it only likes to *always* submit 100 BPM, 150 BPM, 250 BPM and 300 BPM. Didn't try going higher because.. why? ^^ 

For some weird reason it does not submit 200 BPM, it just skips that one, although by logic it should work.

I can't explain why 96 BPM sometimes works, because it did for me twice, and it's totally out of the 100-150-250-300 scheme.

**Comment by FunOrange** [comment]
fixed
